scalar DateTime
type ProductWithQuantity {
    product: Product!
    quantity_ordered: Float!
}
input UUID {
    id: String!
}
input ProductInput {
    quantity: Float!
    id: String!
}

type Order {
    id: String!
    user: User!
    total_price: Float!
    products: [ProductWithQuantity!]!
}
type Query {
    orders: [Order!]!
    showOrder(id: String!): Order
}
type Mutation {
    createOrder(products: [ProductInput!]!): Order!
    deleteOrder(order: UUID!): Order!
}
